/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AuctionItemVariationEnchantments } from './AuctionItemVariationEnchantments';
import type { AuctionItemVariationExtra } from './AuctionItemVariationExtra';
import type { AuctionItemVariationItemAttributes } from './AuctionItemVariationItemAttributes';
import type { AuctionItemVariationPetLevelGroup } from './AuctionItemVariationPetLevelGroup';

export interface AuctionItemVariation {
	/** @nullable */
	rarity?: string | null;
	/** @nullable */
	enchantments?: AuctionItemVariationEnchantments;
	/** @nullable */
	pet?: string | null;
	petLevel?: AuctionItemVariationPetLevelGroup | null;
	/** @nullable */
	itemAttributes?: AuctionItemVariationItemAttributes;
	/** @nullable */
	extra?: AuctionItemVariationExtra;
}
