/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AccountMetaDto } from './AccountMetaDto';
import type { ItemDto } from './ItemDto';

export interface AuctionDto {
	auctionId: string;
	sellerUuid: string;
	sellerProfileUuid: string;
	seller?: AccountMetaDto | null;
	/** @nullable */
	buyerUuid?: string | null;
	/** @nullable */
	buyerProfileUuid?: string | null;
	buyer?: AccountMetaDto | null;
	start: number;
	end: number;
	soldAt: number;
	price: number;
	count: number;
	bin: boolean;
	/** @nullable */
	skyblockId?: string | null;
	variantKey: string;
	/** @nullable */
	itemUuid?: string | null;
	item?: ItemDto | null;
	lastUpdatedAt: string;
	startingBid: number;
	/** @nullable */
	highestBid?: number | null;
}
