/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ConfirmationDto } from './ConfirmationDto';

export interface AuthSessionDto {
	/** Discord user ID */
	id: string;
	/** Discord username */
	username: string;
	/** Discord avatar hash */
	avatar: string;
	/** Primary Minecraft IGN */
	ign: string;
	/**
	 * Formatted Primary Minecraft IGN
	 * @nullable
	 */
	fIgn?: string | null;
	/** Primary Minecraft UUID */
	uuid: string;
	/** List of user roles */
	roles: string[];
	/** List of account flags */
	flags: string[];
	/** The pending confirmation for the user, if any */
	pending_confirmation?: ConfirmationDto | null;
}
