/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { Image } from './Image';

export interface Badge {
	id: number;
	/** @maxLength 50 */
	name: string;
	/** @maxLength 1024 */
	description: string;
	/** @maxLength 512 */
	requirements: string;
	/**
	 * @maxLength 48
	 * @nullable
	 */
	imageId?: string | null;
	image?: Image | null;
	tieToAccount: boolean;
}
