/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ChocolateFactoryRabbitsDto } from './ChocolateFactoryRabbitsDto';

export interface ChocolateFactoryDto {
	chocolate: number;
	totalChocolate: number;
	chocolateSincePrestige: number;
	chocolateSpent: number;
	prestige: number;
	lastViewed: number;
	uniqueRabbits: ChocolateFactoryRabbitsDto;
	totalRabbits: ChocolateFactoryRabbitsDto;
	unlockedZorro: boolean;
	refinedTrufflesConsumed: number;
	cocoaFortuneUpgrades: number;
}
