/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ComposterUpgrades } from './ComposterUpgrades';

export interface ComposterDto {
	organic_matter: number;
	fuel_units: number;
	compost_units: number;
	compost_items: number;
	conversion_ticks: number;
	last_save: number;
	upgrades: ComposterUpgrades;
	/** Last save time in unix seconds */
	lastSave: number;
}
