/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { CheckoutItemDto } from './CheckoutItemDto';
import type { CheckoutRecipientDto } from './CheckoutRecipientDto';

export interface CreateTebexCheckoutRequest {
	items: CheckoutItemDto[];
	recipient?: CheckoutRecipientDto | null;
	/** @nullable */
	creatorCode?: string | null;
	/** @nullable */
	country?: string | null;
	/** @nullable */
	fingerprint?: string | null;
}
