/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

/**
 * Information about the previous record holder at this position, if any.
 */
export interface DisplacedEntryDto {
	uuid: string;
	ign: string;
	discordId: string;
	collected: number;
	previousPosition: number;
}
