/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export interface DungeonBestRun {
	timestamp: number;
	scoreExploration: number;
	scoreSpeed: number;
	scoreSkill: number;
	scoreBonus: number;
	/** @nullable */
	dungeonClass?: string | null;
	elapsedTime: number;
	mobsKilled: number;
	secretsFound: number;
	damageDealt: number;
	deaths: number;
	allyHealing: number;
	damageMitigated: number;
	teammates: string[];
}
