/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { DungeonDataBestScore } from './DungeonDataBestScore';
import type { DungeonDataFastestTime } from './DungeonDataFastestTime';
import type { DungeonDataFastestTimeS } from './DungeonDataFastestTimeS';
import type { DungeonDataFastestTimeSPlus } from './DungeonDataFastestTimeSPlus';
import type { DungeonDataMilestoneCompletions } from './DungeonDataMilestoneCompletions';
import type { DungeonDataMobsKilled } from './DungeonDataMobsKilled';
import type { DungeonDataMostDamageArcher } from './DungeonDataMostDamageArcher';
import type { DungeonDataMostDamageHealer } from './DungeonDataMostDamageHealer';
import type { DungeonDataMostDamageMage } from './DungeonDataMostDamageMage';
import type { DungeonDataMostDamageTank } from './DungeonDataMostDamageTank';
import type { DungeonDataMostHealing } from './DungeonDataMostHealing';
import type { DungeonDataMostMobsKilled } from './DungeonDataMostMobsKilled';
import type { DungeonDataTierCompletions } from './DungeonDataTierCompletions';
import type { DungeonDataTimesPlayed } from './DungeonDataTimesPlayed';
import type { DungeonDataWatcherKills } from './DungeonDataWatcherKills';

export interface DungeonData {
	experience: number;
	highest_tier_completed: number;
	tier_completions: DungeonDataTierCompletions;
	times_played: DungeonDataTimesPlayed;
	best_score: DungeonDataBestScore;
	mobs_killed: DungeonDataMobsKilled;
	most_mobs_killed: DungeonDataMostMobsKilled;
	watcher_kills: DungeonDataWatcherKills;
	most_healing: DungeonDataMostHealing;
	fastest_time: DungeonDataFastestTime;
	fastest_time_s: DungeonDataFastestTimeS;
	fastest_time_s_plus: DungeonDataFastestTimeSPlus;
	most_damage_tank: DungeonDataMostDamageTank;
	most_damage_mage: DungeonDataMostDamageMage;
	most_damage_healer: DungeonDataMostDamageHealer;
	most_damage_archer: DungeonDataMostDamageArcher;
	milestone_completions: DungeonDataMilestoneCompletions;
}
