/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { EventMemberStatus } from './EventMemberStatus';
import type { MemberCosmeticsDto } from './MemberCosmeticsDto';

export interface EventMemberDto {
	/** @nullable */
	playerUuid?: string | null;
	/** @nullable */
	playerName?: string | null;
	/** @nullable */
	profileId?: string | null;
	eventId: string;
	/** @nullable */
	teamId?: string | null;
	status: EventMemberStatus;
	/** @nullable */
	score?: string | null;
	data?: unknown | null;
	/** @nullable */
	lastUpdated?: string | null;
	disqualified: boolean;
	/**
	 * @maxLength 128
	 * @nullable
	 */
	notes?: string | null;
	/** Metadata of the entry */
	meta?: MemberCosmeticsDto | null;
}
