/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ExperimentDataAttempts } from './ExperimentDataAttempts';
import type { ExperimentDataBestScores } from './ExperimentDataBestScores';
import type { ExperimentDataClaims } from './ExperimentDataClaims';

export interface ExperimentData {
	bestScores: ExperimentDataBestScores;
	claims: ExperimentDataClaims;
	attempts: ExperimentDataAttempts;
	bonusClicks: number;
	/** @nullable */
	lastAttempt?: number | null;
	/** @nullable */
	lastClaimed?: number | null;
}
