/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfString } from './ListOfString';

export interface FarmDesignSetup {
	id: string;
	name: string;
	crops: ListOfString;
	instructions: string;
	/** @nullable */
	bps?: number | null;
	/** @nullable */
	speed?: number | null;
	/** @nullable */
	keys?: string | null;
	/** @nullable */
	yaw?: number | null;
	/** @nullable */
	pitch?: number | null;
	/** @nullable */
	notes?: string | null;
}
