/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { FarmingInventoryDto } from './FarmingInventoryDto';
import type { FarmingWeightDtoBonusWeight } from './FarmingWeightDtoBonusWeight';
import type { FarmingWeightDtoCrops } from './FarmingWeightDtoCrops';
import type { FarmingWeightDtoCropWeight } from './FarmingWeightDtoCropWeight';
import type { FarmingWeightDtoUncountedCrops } from './FarmingWeightDtoUncountedCrops';
import type { PestsDto } from './PestsDto';

export interface FarmingWeightDto {
	totalWeight: number;
	/** @nullable */
	crops?: FarmingWeightDtoCrops;
	cropWeight: FarmingWeightDtoCropWeight;
	bonusWeight: FarmingWeightDtoBonusWeight;
	uncountedCrops: FarmingWeightDtoUncountedCrops;
	pests: PestsDto;
	inventory?: FarmingInventoryDto | null;
	lastUpdated: number;
}
