/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ComposterDto } from './ComposterDto';
import type { CropSettingsOfInt32 } from './CropSettingsOfInt32';
import type { CropSettingsOfString } from './CropSettingsOfString';
import type { GardenDtoVisitors } from './GardenDtoVisitors';
import type { GardenUpgradesDto } from './GardenUpgradesDto';
import type { GreenhouseSlotUnlock } from './GreenhouseSlotUnlock';

export interface GardenDto {
	/** Profile ID */
	profileId: string;
	/** Garden experience */
	experience: number;
	/** Total completed visitors */
	completedVisitors: number;
	/** Unique visitors unlocked */
	uniqueVisitors: number;
	/** Crops counted towards milestones */
	crops: CropSettingsOfString;
	/** Crop upgrades */
	cropUpgrades: CropSettingsOfInt32;
	/** List of unlocked plots */
	plots: string[];
	/** Composter data */
	composter: ComposterDto;
	/** Visitor data */
	visitors: GardenDtoVisitors;
	/** Unix timestamp of the last greenhouse growth stage in milliseconds */
	lastGrowthStageTime: number;
	/** Tracked unlocked greenhouse slots */
	greenhouseSlots: GreenhouseSlotUnlock[];
	/** Greenhouse upgrades */
	gardenUpgrades: GardenUpgradesDto;
	/** Last save time in unix seconds */
	lastSave: string;
}
