/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { HypixelGuildStatsDto } from './HypixelGuildStatsDto';

export interface HypixelGuildDetailsDto {
	id: string;
	name: string;
	createdAt: number;
	/** @nullable */
	tag?: string | null;
	/** @nullable */
	tagColor?: string | null;
	memberCount: number;
	lastUpdated: number;
	stats?: HypixelGuildStatsDto | null;
	/** Populated when sorting guilds by a specific collection or skill */
	amount: number;
}
