/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ItemAttributes } from './ItemAttributes';
import type { ItemDtoEnchantments } from './ItemDtoEnchantments';
import type { ItemDtoGems } from './ItemDtoGems';
import type { ItemDtoItemAttributes } from './ItemDtoItemAttributes';
import type { ItemPetInfoDto } from './ItemPetInfoDto';

export interface ItemDto {
	/** Old Minecraft id of the item */
	id: number;
	/** Minecraft stack count of the item */
	count: number;
	/** Minecraft damage value of the item */
	damage: number;
	/**
	 * Skyblock ID of the item
	 * @nullable
	 */
	skyblockId?: string | null;
	/**
	 * Item UUID to uniquely identify a specific instance of this item
	 * @nullable
	 */
	uuid?: string | null;
	/**
	 * Item name, first line of the lore
	 * @nullable
	 */
	name?: string | null;
	/**
	 * List of item lore in order
	 * @nullable
	 */
	lore?: string[] | null;
	/**
	 * Applied enchantments with their levels
	 * @nullable
	 */
	enchantments?: ItemDtoEnchantments;
	/** ExtraAttributes not included elsewhere */
	attributes?: ItemAttributes | null;
	/**
	 * ExtraAtrributes.Attributes for attribute shards
	 * @nullable
	 */
	itemAttributes?: ItemDtoItemAttributes;
	/**
	 * Applied gems with gem rarity, null for an unlocked gem slot without a gem
	 * @nullable
	 */
	gems?: ItemDtoGems;
	/** Pet info if item is a pet */
	petInfo?: ItemPetInfoDto | null;
	/**
	 * Image url for the item
	 * @nullable
	 */
	imageUrl?: string | null;
	/**
	 * Texture id for the item, used to look up the image in our image service
	 * @nullable
	 */
	textureId?: string | null;
	/**
	 * Slot identifier where the item was located, if applicable
	 * @nullable
	 */
	slot?: string | null;
}
