/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { CatacombsRequirements } from './CatacombsRequirements';
import type { DungeonItemConversionCost } from './DungeonItemConversionCost';
import type { ItemGemstoneSlot } from './ItemGemstoneSlot';
import type { ItemMuseumData } from './ItemMuseumData';
import type { ItemRequirement } from './ItemRequirement';
import type { ItemResponseStats } from './ItemResponseStats';
import type { ItemSkin } from './ItemSkin';
import type { JsonDocument } from './JsonDocument';
import type { UpgradeCosts } from './UpgradeCosts';

export interface ItemResponse {
	/** @nullable */
	id?: string | null;
	/** @nullable */
	material?: string | null;
	/** @nullable */
	color?: string | null;
	durability: number;
	skin?: ItemSkin | null;
	/** @nullable */
	name?: string | null;
	/** @nullable */
	category?: string | null;
	/** @nullable */
	tier?: string | null;
	unstackable: boolean;
	glowing: boolean;
	npc_sell_price: number;
	can_auction: boolean;
	can_trade: boolean;
	can_place: boolean;
	/** @nullable */
	gemstone_slots?: ItemGemstoneSlot[] | null;
	/** @nullable */
	requirements?: ItemRequirement[] | null;
	museum: boolean;
	museum_data?: ItemMuseumData | null;
	/** @nullable */
	stats?: ItemResponseStats;
	generator_tier: number;
	dungeon_item_conversion_cost?: DungeonItemConversionCost | null;
	/** @nullable */
	upgrade_costs?: UpgradeCosts[][] | null;
	/** @nullable */
	catacombs_requirements?: CatacombsRequirements[] | null;
	hide_from_viewrecipe_command: boolean;
	salvagable_from_recipe: boolean;
	item_specific?: JsonDocument | null;
	[key: string]: unknown;
}
