/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ItemAttributesInventoryData } from './ItemAttributesInventoryData';
import type { ItemAttributesRunes } from './ItemAttributesRunes';
import type { ItemEffectAttribute } from './ItemEffectAttribute';
import type { ItemRodPartAttribute } from './ItemRodPartAttribute';
import type { ItemSoulAttribute } from './ItemSoulAttribute';

export interface ItemAttributes {
	/** @nullable */
	runes?: ItemAttributesRunes;
	/** @nullable */
	effects?: ItemEffectAttribute[] | null;
	/** @nullable */
	necromancer_souls?: ItemSoulAttribute[] | null;
	hook?: ItemRodPartAttribute | null;
	line?: ItemRodPartAttribute | null;
	sinker?: ItemRodPartAttribute | null;
	/** @nullable */
	ability_scroll?: string[] | null;
	/** @nullable */
	inventory_data?: ItemAttributesInventoryData;
	[key: string]: unknown;
}
