/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ItemMuseumDataArmorSetDonationXp } from './ItemMuseumDataArmorSetDonationXp';
import type { ItemMuseumDataParent } from './ItemMuseumDataParent';

export interface ItemMuseumData {
	donation_xp: number;
	parent: ItemMuseumDataParent;
	/** @nullable */
	type?: string | null;
	/** @nullable */
	armor_set_donation_xp?: ItemMuseumDataArmorSetDonationXp;
	/** @nullable */
	game_stage?: string | null;
	[key: string]: unknown;
}
