/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ManagedResourcePackOwnerDto } from './ManagedResourcePackOwnerDto';
import type { ManagedResourcePackVersionDto } from './ManagedResourcePackVersionDto';

export interface ManagedResourcePackDto {
	id: number;
	slug: string;
	displayName: string;
	directoryName: string;
	modrinthProjectUrl: string;
	modrinthProjectSlug: string;
	authors: string[];
	/** @nullable */
	notes?: string | null;
	createdAt: string;
	updatedAt: string;
	liveVersion?: ManagedResourcePackVersionDto | null;
	stagedVersion?: ManagedResourcePackVersionDto | null;
	owners: ManagedResourcePackOwnerDto[];
}
