/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AbiphoneData } from './AbiphoneData';
import type { AccessoryData } from './AccessoryData';
import type { AccessoryDerivationsDto } from './AccessoryDerivationsDto';
import type { BestiaryData } from './BestiaryData';
import type { BestiaryDerivationsDto } from './BestiaryDerivationsDto';
import type { CarnivalData } from './CarnivalData';
import type { CrimsonIsleStatsDto } from './CrimsonIsleStatsDto';
import type { DungeonsStatsDto } from './DungeonsStatsDto';
import type { EnchantingData } from './EnchantingData';
import type { FishingStatsDto } from './FishingStatsDto';
import type { ForagingStatsDto } from './ForagingStatsDto';
import type { HarpQuestData } from './HarpQuestData';
import type { MiningStatsDto } from './MiningStatsDto';
import type { MiscStatsDto } from './MiscStatsDto';
import type { PlayerStatsDto } from './PlayerStatsDto';
import type { RiftStatsDto } from './RiftStatsDto';
import type { SeasonOfJerryStatsDto } from './SeasonOfJerryStatsDto';
import type { SkillsStatsDto } from './SkillsStatsDto';
import type { SlayerData } from './SlayerData';

export interface MemberStatsDto {
	dungeons?: DungeonsStatsDto | null;
	slayer?: SlayerData | null;
	mining?: MiningStatsDto | null;
	bestiary?: BestiaryData | null;
	/** Derived bestiary aggregates (per-base-mob kill totals, top mobs, totals) computed from
  Bestiary. Hypixel exposes per-tier kill keys like "wolf_1", "wolf_2"; this
  summary collapses those into a single entry per base mob id. */
	bestiaryDerivations?: BestiaryDerivationsDto | null;
	crimsonIsle?: CrimsonIsleStatsDto | null;
	fishing?: FishingStatsDto | null;
	rift?: RiftStatsDto | null;
	enchanting?: EnchantingData | null;
	foraging?: ForagingStatsDto | null;
	accessories?: AccessoryData | null;
	/** Derived accessory bag aggregates: counts of recombobulated/reforged/enriched talismans,
  owned ids, tuning slot progression, etc. Sourced from the parsed talisman_bag
  inventory plus Accessories. */
	accessoryDerivations?: AccessoryDerivationsDto | null;
	/** Typed Season-of-Jerry counters extracted from player_stats.winter when the dict
  has any recognised keys. Null otherwise. */
	seasonOfJerry?: SeasonOfJerryStatsDto | null;
	playerStats?: PlayerStatsDto | null;
	miscStats?: MiscStatsDto | null;
	abiphone?: AbiphoneData | null;
	harpQuest?: HarpQuestData | null;
	carnival?: CarnivalData | null;
	/** Aggregate skill stats (total XP, average level, level caps, per-skill level details).
  Lives here so SkillsDto can remain a flat per-skill XP map. */
	skills?: SkillsStatsDto | null;
	lastUpdated: number;
}
