/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ForgeProcess } from './ForgeProcess';
import type { GlaciteStatsDto } from './GlaciteStatsDto';
import type { MilestoneProgressDto } from './MilestoneProgressDto';
import type { MiningStatsDtoCrystals } from './MiningStatsDtoCrystals';
import type { MiningStatsDtoNodes } from './MiningStatsDtoNodes';
import type { MiningStatsDtoNodeToggles } from './MiningStatsDtoNodeToggles';
import type { PowderStatsDto } from './PowderStatsDto';

export interface MiningStatsDto {
	experience: number;
	hotmLevel: number;
	hotmProgress: number;
	peakOfTheMountainLevel: number;
	tokens: number;
	tokensSpent: number;
	/** @nullable */
	selectedPickaxeAbility?: string | null;
	crystalHollowsLastAccess: number;
	crystalNucleusRuns: number;
	commissionMilestone: number;
	powder: PowderStatsDto;
	crystals: MiningStatsDtoCrystals;
	nodes: MiningStatsDtoNodes;
	nodeToggles: MiningStatsDtoNodeToggles;
	forgeProcesses: ForgeProcess[];
	glacite?: GlaciteStatsDto | null;
	/** Derived Rock pet milestone progress (driven by player_stats.pets.milestones.ores_mined). */
	rockMilestone?: MilestoneProgressDto | null;
}
