/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { FestivalStatsDto } from './FestivalStatsDto';
import type { MiscStatsDtoEssence } from './MiscStatsDtoEssence';
import type { MiscStatsDtoLevelingCompletions } from './MiscStatsDtoLevelingCompletions';
import type { PetScoreRewardDto } from './PetScoreRewardDto';

export interface MiscStatsDto {
	essence: MiscStatsDtoEssence;
	dragonsSacrificed: number;
	firstJoin: number;
	firstJoinHub: number;
	skyblockLevel: number;
	skyblockProgress: number;
	soulflow: number;
	/** @nullable */
	favoriteArrow?: string | null;
	refinedJyrreUses: number;
	pelts: number;
	levelingCompletions: MiscStatsDtoLevelingCompletions;
	highestPetScore: number;
	/** Cumulative pet score reward stats unlocked by HighestPetScore. */
	unlockedPetScoreRewards: PetScoreRewardDto[];
	festivals: FestivalStatsDto;
}
