/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { PetSummaryDtoRarityCounts } from './PetSummaryDtoRarityCounts';
import type { PetSummaryEntryDto } from './PetSummaryEntryDto';

/**
 * Compact summary of the player's pet roster.
 */
export interface PetSummaryDto {
	totalPets: number;
	maxLevelPets: number;
	totalCandyUsed: number;
	totalSkins: number;
	rarityCounts: PetSummaryDtoRarityCounts;
	activePet?: PetSummaryEntryDto | null;
	topPets: PetSummaryEntryDto[];
}
