/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AuctionStatsData } from './AuctionStatsData';
import type { DamageStatsDto } from './DamageStatsDto';
import type { DragonFightData } from './DragonFightData';
import type { FairySoulsDto } from './FairySoulsDto';
import type { GiftsDto } from './GiftsDto';
import type { KillsDeathsDto } from './KillsDeathsDto';
import type { MythosData } from './MythosData';
import type { PlayerStatsDerivationsDto } from './PlayerStatsDerivationsDto';
import type { PlayerStatsDtoPetMilestones } from './PlayerStatsDtoPetMilestones';
import type { PlayerStatsDtoSpooky } from './PlayerStatsDtoSpooky';
import type { PlayerStatsDtoWinter } from './PlayerStatsDtoWinter';

export interface PlayerStatsDto {
	fairySouls: FairySoulsDto;
	killsDeaths: KillsDeathsDto;
	damage: DamageStatsDto;
	gifts: GiftsDto;
	glowingMushroomsBroken: number;
	mythos?: MythosData | null;
	/** @nullable */
	spooky?: PlayerStatsDtoSpooky;
	/** @nullable */
	winter?: PlayerStatsDtoWinter;
	/** @nullable */
	petMilestones?: PlayerStatsDtoPetMilestones;
	dragonFight?: DragonFightData | null;
	auctions?: AuctionStatsData | null;
	/** Aggregated derivations over KillsDeaths dictionaries: top kills/deaths,
  totals, K/D ratio, and notable boss-mob counts. */
	derivations?: PlayerStatsDerivationsDto | null;
}
