/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { HypixelGuildMemberDetailsDto } from './HypixelGuildMemberDetailsDto';
import type { SocialMediaLinksDto } from './SocialMediaLinksDto';

export interface PlayerDataDto {
	uuid: string;
	/** @nullable */
	displayname?: string | null;
	firstLogin: number;
	lastLogin: number;
	lastLogout: number;
	karma: number;
	networkExp: number;
	guildMember?: HypixelGuildMemberDetailsDto | null;
	rewardHighScore: number;
	rewardScore: number;
	rewardStreak: number;
	totalDailyRewards: number;
	totalRewards: number;
	/** @nullable */
	prefix?: string | null;
	/** @nullable */
	rank?: string | null;
	/** @nullable */
	packageRank?: string | null;
	/** @nullable */
	newPackageRank?: string | null;
	/** @nullable */
	rankPlusColor?: string | null;
	/** @nullable */
	monthlyPackageRank?: string | null;
	/** @nullable */
	mostRecentMonthlyPackageRank?: string | null;
	/** @nullable */
	monthlyRankColor?: string | null;
	socialMedia?: SocialMediaLinksDto | null;
}
