/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { GuildChannelDto } from './GuildChannelDto';
import type { GuildFeatures } from './GuildFeatures';
import type { GuildRoleDto } from './GuildRoleDto';
import type { ImageAttachmentDto } from './ImageAttachmentDto';

export interface PrivateGuildDto {
	id: string;
	name: string;
	public: boolean;
	features: GuildFeatures;
	icon?: ImageAttachmentDto | null;
	banner?: ImageAttachmentDto | null;
	/** @nullable */
	inviteCode?: string | null;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	adminRole?: string | null;
	/** @nullable */
	botPermissions?: string | null;
	botPermissionsNew: string;
	discordFeatures: string[];
	memberCount: number;
	channels: GuildChannelDto[];
	roles: GuildRoleDto[];
}
