/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ImageAttachmentDto } from './ImageAttachmentDto';
import type { ProductType } from './ProductType';
import type { TebexProductSettingsDto } from './TebexProductSettingsDto';
import type { UnlockedProductFeaturesDto } from './UnlockedProductFeaturesDto';
import type { WeightStyleLinkedDto } from './WeightStyleLinkedDto';

export interface ProductDto {
	/** Product ID */
	id: string;
	/** Product name */
	name: string;
	/** Slug of the product */
	slug: string;
	/** Product price */
	price: number;
	/**
	 * Product description
	 * @nullable
	 */
	description?: string | null;
	/** If the product is available for purchase */
	available: boolean;
	/** Type of product */
	type: ProductType;
	/** Features of the product */
	features: UnlockedProductFeaturesDto;
	/** Unlocked weight styles */
	weightStyles: WeightStyleLinkedDto[];
	/** Product thumbnail */
	thumbnail?: ImageAttachmentDto | null;
	/** Product Images */
	images: ImageAttachmentDto[];
	/** Discord flags */
	flags: number;
	isSubscription: boolean;
	isGuildSubscription: boolean;
	isUserSubscription: boolean;
	/**
	 * Product release date
	 * @nullable
	 */
	releasedAt?: string | null;
	/** Tebex-specific checkout settings for the product */
	tebex?: TebexProductSettingsDto | null;
}
