/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ApiAccessDto } from './ApiAccessDto';
import type { ChocolateFactoryDto } from './ChocolateFactoryDto';
import type { FarmingWeightDto } from './FarmingWeightDto';
import type { GardenDto } from './GardenDto';
import type { HypixelInventoryOverviewDto } from './HypixelInventoryOverviewDto';
import type { JacobDataDto } from './JacobDataDto';
import type { MemberCosmeticsDto } from './MemberCosmeticsDto';
import type { PetDto } from './PetDto';
import type { ProfileEventMemberDto } from './ProfileEventMemberDto';
import type { ProfileMemberDataDto } from './ProfileMemberDataDto';
import type { ProfileMemberDtoCollections } from './ProfileMemberDtoCollections';
import type { ProfileMemberDtoCollectionTiers } from './ProfileMemberDtoCollectionTiers';
import type { ProfileMemberDtoCraftedMinions } from './ProfileMemberDtoCraftedMinions';
import type { ProfileMemberDtoSacks } from './ProfileMemberDtoSacks';
import type { ProfileMemberNetworthDto } from './ProfileMemberNetworthDto';
import type { SkillsDto } from './SkillsDto';
import type { UnparsedApiDataDto } from './UnparsedApiDataDto';

export interface ProfileMemberDto {
	profileId: string;
	playerUuid: string;
	profileName: string;
	api: ApiAccessDto;
	skyblockXp: number;
	socialXp: number;
	purse: number;
	bankBalance: number;
	personalBank: number;
	networth: ProfileMemberNetworthDto;
	meta?: MemberCosmeticsDto | null;
	collections: ProfileMemberDtoCollections;
	collectionTiers: ProfileMemberDtoCollectionTiers;
	craftedMinions: ProfileMemberDtoCraftedMinions;
	sacks: ProfileMemberDtoSacks;
	pets: PetDto[];
	unparsed: UnparsedApiDataDto;
	jacob: JacobDataDto;
	farmingWeight: FarmingWeightDto;
	garden?: GardenDto | null;
	skills: SkillsDto;
	memberData: ProfileMemberDataDto;
	chocolateFactory: ChocolateFactoryDto;
	events: ProfileEventMemberDto[];
	inventories: HypixelInventoryOverviewDto[];
	isSelected: boolean;
	wasRemoved: boolean;
	lastUpdated: number;
	lastDataChanged: number;
}
