/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ProfileMemberGardenChipsDataDto } from './ProfileMemberGardenChipsDataDto';
import type { ProfileMemberGardenDataDtoMutations } from './ProfileMemberGardenDataDtoMutations';

export interface ProfileMemberGardenDataDto {
	copper: number;
	dnaMilestone: number;
	chips?: ProfileMemberGardenChipsDataDto | null;
	mutations: ProfileMemberGardenDataDtoMutations;
}
