/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ApiAccessDto } from './ApiAccessDto';
import type { ChocolateFactoryDto } from './ChocolateFactoryDto';
import type { CollectionSummaryDto } from './CollectionSummaryDto';
import type { FarmingWeightDto } from './FarmingWeightDto';
import type { GardenDto } from './GardenDto';
import type { HypixelInventoryOverviewDto } from './HypixelInventoryOverviewDto';
import type { JacobDataDto } from './JacobDataDto';
import type { MemberCosmeticsDto } from './MemberCosmeticsDto';
import type { MemberStatsDto } from './MemberStatsDto';
import type { MinionSummaryDto } from './MinionSummaryDto';
import type { PetDto } from './PetDto';
import type { PetSummaryDto } from './PetSummaryDto';
import type { ProfileEventMemberDto } from './ProfileEventMemberDto';
import type { ProfileMemberDataDto } from './ProfileMemberDataDto';
import type { ProfileMemberDtoCollections } from './ProfileMemberDtoCollections';
import type { ProfileMemberDtoCollectionTiers } from './ProfileMemberDtoCollectionTiers';
import type { ProfileMemberDtoCraftedMinions } from './ProfileMemberDtoCraftedMinions';
import type { ProfileMemberDtoSacks } from './ProfileMemberDtoSacks';
import type { ProfileMemberNetworthDto } from './ProfileMemberNetworthDto';
import type { SkillsDto } from './SkillsDto';
import type { UnparsedApiDataDto } from './UnparsedApiDataDto';

export interface ProfileMemberDto {
	profileId: string;
	playerUuid: string;
	profileName: string;
	api: ApiAccessDto;
	skyblockXp: number;
	socialXp: number;
	purse: number;
	bankBalance: number;
	personalBank: number;
	cookieBuffActive: boolean;
	networth: ProfileMemberNetworthDto;
	meta?: MemberCosmeticsDto | null;
	collections: ProfileMemberDtoCollections;
	collectionTiers: ProfileMemberDtoCollectionTiers;
	craftedMinions: ProfileMemberDtoCraftedMinions;
	sacks: ProfileMemberDtoSacks;
	pets: PetDto[];
	unparsed: UnparsedApiDataDto;
	jacob: JacobDataDto;
	farmingWeight: FarmingWeightDto;
	garden?: GardenDto | null;
	skills: SkillsDto;
	memberData: ProfileMemberDataDto;
	chocolateFactory: ChocolateFactoryDto;
	events: ProfileEventMemberDto[];
	inventories: HypixelInventoryOverviewDto[];
	stats?: MemberStatsDto | null;
	/** Derived summary of crafted minion progression (slots and unique tiers) computed from
  CraftedMinions and the staged minion metadata. */
	minionSummary?: MinionSummaryDto | null;
	/** Derived summary of boss/Kuudra collection tier progression computed from
  Collections and the staged collection metadata. */
	collectionSummary?: CollectionSummaryDto | null;
	/** Compact pet roster summary (totals, active pet, top pets by experience). Computed from
  Pets alone; does not require metadata. */
	petSummary?: PetSummaryDto | null;
	isSelected: boolean;
	wasRemoved: boolean;
	lastUpdated: number;
	lastDataChanged: number;
}
