/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { DungeonPlayerClasses } from './DungeonPlayerClasses';
import type { DungeonTypes } from './DungeonTypes';
import type { RawDungeonsResponseDungeonJournal } from './RawDungeonsResponseDungeonJournal';

export interface RawDungeonsResponse {
	dungeon_types?: DungeonTypes | null;
	player_classes?: DungeonPlayerClasses | null;
	/** @nullable */
	selected_dungeon_class?: string | null;
	secrets: number;
	/** @nullable */
	dungeon_journal?: RawDungeonsResponseDungeonJournal;
}
