/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { TebexRecipientMode } from './TebexRecipientMode';

export interface ResendGiftRequest {
	orderItemIds: string[];
	mode?: TebexRecipientMode | null;
	/** @nullable */
	playerUuidOrIgn?: string | null;
	/** @nullable */
	guildId?: number | null;
	/** @nullable */
	message?: string | null;
}
