/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ContestParticipationDto } from './ContestParticipationDto';
import type { DisplacedEntryDto } from './DisplacedEntryDto';
import type { SubmitterInfoDto } from './SubmitterInfoDto';

export interface ScoreChangeDto {
	crop: string;
	newPosition: number;
	oldPosition: number;
	submitter: SubmitterInfoDto;
	record: ContestParticipationDto;
	displacedEntry?: DisplacedEntryDto | null;
	knockedOutEntry?: DisplacedEntryDto | null;
	/**
	 * The amount the submitter improved their own score (if applicable).
	 * @nullable
	 */
	improvement?: number | null;
	isNewHighScore: boolean;
	isImprovement: boolean;
}
