/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AuctionItemDto } from './AuctionItemDto';
import type { BazaarProductSummaryDto } from './BazaarProductSummaryDto';
import type { ItemResponse } from './ItemResponse';

export interface SkyblockItemResponse {
	itemId: string;
	/** @nullable */
	name?: string | null;
	/** Data from the Hypixel items endpoint */
	data?: ItemResponse | null;
	bazaar?: BazaarProductSummaryDto | null;
	/** @nullable */
	auctions?: AuctionItemDto[] | null;
}
