/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { BazaarProductSummaryDto } from './BazaarProductSummaryDto';
import type { ItemResponse } from './ItemResponse';
import type { ListOfAuctionItemDto } from './ListOfAuctionItemDto';

export interface SkyblockItemResponse {
	itemId: string;
	/** @nullable */
	name?: string | null;
	data?: ItemResponse | null;
	bazaar?: BazaarProductSummaryDto | null;
	auctions?: ListOfAuctionItemDto | null;
}
