/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { SlayerBossDataBossAttempts } from './SlayerBossDataBossAttempts';
import type { SlayerBossDataBossKills } from './SlayerBossDataBossKills';
import type { SlayerBossDataClaimedLevels } from './SlayerBossDataClaimedLevels';

export interface SlayerBossData {
	xp: number;
	level: number;
	maxLevel: number;
	progress: number;
	xpForNext: number;
	claimedLevels: SlayerBossDataClaimedLevels;
	bossKills: SlayerBossDataBossKills;
	bossAttempts: SlayerBossDataBossAttempts;
}
