/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { PurchaseMode } from './PurchaseMode';
import type { TebexExpectedBasketItem } from './TebexExpectedBasketItem';
import type { TebexRecipientSnapshot } from './TebexRecipientSnapshot';
import type { TebexSaleSnapshot } from './TebexSaleSnapshot';

export interface TebexExpectedBasketSnapshot {
	orderId: string;
	buyerId: number;
	purchaseMode: PurchaseMode;
	/** @nullable */
	creatorCode?: string | null;
	/** @nullable */
	country?: string | null;
	/** @nullable */
	fingerprint?: string | null;
	sale?: TebexSaleSnapshot | null;
	recipient?: TebexRecipientSnapshot | null;
	items: TebexExpectedBasketItem[];
}
