/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export type UpgradeCostType = (typeof UpgradeCostType)[keyof typeof UpgradeCostType];

export const UpgradeCostType = {
	Unknown: 0,
	Item: 1,
	Essence: 2,
	Coins: 3,
	Motes: 4,
	Copper: 5,
	Gems: 6,
	Bits: 7,
	JacobMedal: 8,
	Pelts: 9,
} as const;
