/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ConfiguredProductFeaturesDto } from './ConfiguredProductFeaturesDto';
import type { FortuneSettingsDto } from './FortuneSettingsDto';
import type { MiscUserSettingsDto } from './MiscUserSettingsDto';
import type { WeightStyleLinkedDto } from './WeightStyleLinkedDto';

export interface UserSettingsDto {
	/**
	 * Custom name prefix
	 * @nullable
	 */
	prefix?: string | null;
	/**
	 * Custom name suffix
	 * @nullable
	 */
	suffix?: string | null;
	/** Configurated features for the user */
	features?: ConfiguredProductFeaturesDto | null;
	/** Selected weight style for the user */
	weightStyle?: WeightStyleLinkedDto | null;
	/** Selected leaderboard style for the user */
	leaderboardStyle?: WeightStyleLinkedDto | null;
	/** Selected name style for the user */
	nameStyle?: WeightStyleLinkedDto | null;
	/** Fortune settings for the user */
	fortune?: FortuneSettingsDto | null;
	/** Misc other settings */
	misc?: MiscUserSettingsDto | null;
}
