/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AuthorDto } from './AuthorDto';
import type { ImageAttachmentDto } from './ImageAttachmentDto';
import type { LeaderboardStyleDataDto } from './LeaderboardStyleDataDto';
import type { ParentProductDto } from './ParentProductDto';
import type { WeightStyleDataDto } from './WeightStyleDataDto';
import type { WeightStyleWithDataDtoImageRefs } from './WeightStyleWithDataDtoImageRefs';

export interface WeightStyleWithDataDto {
	id: number;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	styleFormatter?: string | null;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	name?: string | null;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	collection?: string | null;
	/**
	 * @maxLength 1024
	 * @nullable
	 */
	description?: string | null;
	image?: ImageAttachmentDto | null;
	author?: AuthorDto | null;
	images: ImageAttachmentDto[];
	products: ParentProductDto[];
	data?: WeightStyleDataDto | null;
	leaderboard?: LeaderboardStyleDataDto | null;
	imageRefs: WeightStyleWithDataDtoImageRefs;
}
