/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { WeightStyleBackgroundDto } from './WeightStyleBackgroundDto';
import type { WeightStyleElementDto } from './WeightStyleElementDto';
import type { WeightStyleGradientDto } from './WeightStyleGradientDto';

export interface WeightStyleElementsDto {
	background: WeightStyleBackgroundDto;
	/** @nullable */
	gradients?: WeightStyleGradientDto[] | null;
	name?: WeightStyleElementDto | null;
	weight?: WeightStyleElementDto | null;
	label?: WeightStyleElementDto | null;
	head?: WeightStyleElementDto | null;
	badge?: WeightStyleElementDto | null;
	rank?: WeightStyleElementDto | null;
	rankWithBadge?: WeightStyleElementDto | null;
}
