/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { WeightStyleElementOutlineDto } from './WeightStyleElementOutlineDto';
import type { WeightStylePositionDto } from './WeightStylePositionDto';
import type { WeightStyleTextBackgroundDto } from './WeightStyleTextBackgroundDto';

export interface WeightStyleElementDto {
	/** @nullable */
	font?: string | null;
	/** @nullable */
	fill?: string | null;
	/** @nullable */
	fontSize?: number | null;
	position: WeightStylePositionDto;
	/** @nullable */
	maxWidth?: number | null;
	/** @nullable */
	maxHeight?: number | null;
	outline?: WeightStyleElementOutlineDto | null;
	background?: WeightStyleTextBackgroundDto | null;
}
