/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { WeightStyleBackgroundRect } from './WeightStyleBackgroundRect';
import type { WeightStylePosition } from './WeightStylePosition';

export interface WeightStyleBackground {
	size?: WeightStylePosition | null;
	/** @nullable */
	fill?: string | null;
	/** @nullable */
	rects?: WeightStyleBackgroundRect[] | null;
	/** @nullable */
	imageUrl?: string | null;
	/** @nullable */
	radius?: number | null;
	/** @nullable */
	opacity?: number | null;
}
