/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { WeightStyleBackground } from './WeightStyleBackground';
import type { WeightStyleElement } from './WeightStyleElement';
import type { WeightStyleGradient } from './WeightStyleGradient';

export interface WeightStyleElements {
	background: WeightStyleBackground;
	/** @nullable */
	gradients?: WeightStyleGradient[] | null;
	name?: WeightStyleElement | null;
	weight?: WeightStyleElement | null;
	label?: WeightStyleElement | null;
	head?: WeightStyleElement | null;
	badge?: WeightStyleElement | null;
	rank?: WeightStyleElement | null;
	rankWithBadge?: WeightStyleElement | null;
}
