/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

import * as dotenv from 'dotenv';
import type {
	AuthorizedAccountDto,
	ContestBracketsDetailsDto,
	DisableContestPingsPingsParams,
	ErrorResponse,
	FarmingInventoryDto,
	FarmingWeightAllProfilesDto,
	FullGuideDto,
	GetContestsAtTimestampParams,
	GetCropGraphsParams,
	GetCurrentMedalBracketsParams,
	GetGuideParams,
	GetLeaderboardParams,
	GetMedalBracketsGraphParams,
	GetMedalBracketsParams,
	GetPlayerLeaderboardRanksParams,
	GetPlayerRank1Params,
	GetPlayerRank2Params,
	GetSkillGraphsParams,
	GetSpecifiedSkyblockItemsRequest,
	GetSpecifiedSkyblockItemsResponse,
	GetWeightForProfilesParams,
	GuildJacobLeaderboardFeature,
	IncomingAccountDto,
	IncomingGuildChannelDto,
	IncomingGuildRoleDto,
	LeaderboardDto,
	LeaderboardPositionDto,
	LeaderboardRanksResponse,
	LeaderboardsResponse,
	ListOfContestBracketsDetailsDto,
	ListOfContestParticipationDto,
	ListOfContestPingsFeatureDto,
	ListOfCropCollectionsDataPointDto,
	ListOfJacobContestWithParticipationsDto,
	ListOfSkillsDataPointDto,
	ListOfString,
	ListOfWeightStyleListDto,
	MinecraftAccountDto,
	PlayerDataDto,
	PrivateGuildDto,
	ProblemDetails,
	ProductDto,
	ProfileMemberDto,
	SearchAccountsParams,
	SubmitScoreParams,
	SubmitScoreResponse,
	UpdateJacobFeatureParams,
	UpdateJacobFeatureRequestUpdateJacobFeature,
	UpdateNotificationDeliveryAttemptRequest,
	UserSettingsDto,
	YearlyContestsDto,
} from '../schemas';
import { customFetch } from '../util/custom-fetch';

dotenv.config();
const ELITE_API_URL = process.env.ELITE_API_URL;

export type searchAccountsResponse200 = {
	data: ListOfString;
	status: 200;
};

export type searchAccountsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type searchAccountsResponseSuccess = searchAccountsResponse200 & {
	headers: Headers;
};
export type searchAccountsResponseError = searchAccountsResponse400 & {
	headers: Headers;
};

export type searchAccountsResponse = searchAccountsResponseSuccess | searchAccountsResponseError;

export const getSearchAccountsUrl = (params: SearchAccountsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/account/search?${stringifiedParams}`
		: `${ELITE_API_URL}/account/search`;
};

/**
 * @summary Search for Minecraft Account
 */
export const searchAccounts = async (params: SearchAccountsParams, options?: RequestInit) => {
	return customFetch<searchAccountsResponse>(getSearchAccountsUrl(params), {
		...options,
		method: 'GET',
	});
};

export type getAccountSettingsResponse200 = {
	data: UserSettingsDto;
	status: 200;
};

export type getAccountSettingsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getAccountSettingsResponseSuccess = getAccountSettingsResponse200 & {
	headers: Headers;
};
export type getAccountSettingsResponseError = getAccountSettingsResponse400 & {
	headers: Headers;
};

export type getAccountSettingsResponse = getAccountSettingsResponseSuccess | getAccountSettingsResponseError;

export const getGetAccountSettingsUrl = (discordId: number) => {
	return `${ELITE_API_URL}/account/${discordId}/settings`;
};

/**
 * @summary Get Account Settings
 */
export const getAccountSettings = async (discordId: number, options?: RequestInit) => {
	return customFetch<getAccountSettingsResponse>(getGetAccountSettingsUrl(discordId), {
		...options,
		method: 'GET',
	});
};

export type getAccountResponse200 = {
	data: MinecraftAccountDto;
	status: 200;
};

export type getAccountResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getAccountResponseSuccess = getAccountResponse200 & {
	headers: Headers;
};
export type getAccountResponseError = getAccountResponse400 & {
	headers: Headers;
};

export type getAccountResponse = getAccountResponseSuccess | getAccountResponseError;

export const getGetAccountUrl = (player: string) => {
	return `${ELITE_API_URL}/account/${player}`;
};

/**
 * Retrieves the Minecraft account information for a given player, along with an overview of their profiles and player data.
 * @summary Get Account
 */
export const getAccount = async (player: string, options?: RequestInit) => {
	return customFetch<getAccountResponse>(getGetAccountUrl(player), {
		...options,
		method: 'GET',
	});
};

export type updateDiscordAccountResponse200 = {
	data: AuthorizedAccountDto;
	status: 200;
};

export type updateDiscordAccountResponseSuccess = updateDiscordAccountResponse200 & {
	headers: Headers;
};

export type updateDiscordAccountResponse = updateDiscordAccountResponseSuccess;

export const getUpdateDiscordAccountUrl = () => {
	return `${ELITE_API_URL}/bot/account`;
};

/**
 * @summary Update user Discord account
 */
export const updateDiscordAccount = async (incomingAccountDto: IncomingAccountDto, options?: RequestInit) => {
	return customFetch<updateDiscordAccountResponse>(getUpdateDiscordAccountUrl(), {
		...options,
		method: 'PATCH',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(incomingAccountDto),
	});
};

export type refreshUserPurchasesResponse204 = {
	data: void;
	status: 204;
};

export type refreshUserPurchasesResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type refreshUserPurchasesResponseSuccess = refreshUserPurchasesResponse204 & {
	headers: Headers;
};
export type refreshUserPurchasesResponseError = refreshUserPurchasesResponse400 & {
	headers: Headers;
};

export type refreshUserPurchasesResponse = refreshUserPurchasesResponseSuccess | refreshUserPurchasesResponseError;

export const getRefreshUserPurchasesUrl = (discordId: number) => {
	return `${ELITE_API_URL}/bot/account/${discordId}/purchases`;
};

/**
 * @summary Refresh User Purchases
 */
export const refreshUserPurchases = async (discordId: number, options?: RequestInit) => {
	return customFetch<refreshUserPurchasesResponse>(getRefreshUserPurchasesUrl(discordId), {
		...options,
		method: 'POST',
	});
};

export type linkAccountBotResponse204 = {
	data: void;
	status: 204;
};

export type linkAccountBotResponse400 = {
	data: ProblemDetails;
	status: 400;
};

export type linkAccountBotResponseSuccess = linkAccountBotResponse204 & {
	headers: Headers;
};
export type linkAccountBotResponseError = linkAccountBotResponse400 & {
	headers: Headers;
};

export type linkAccountBotResponse = linkAccountBotResponseSuccess | linkAccountBotResponseError;

export const getLinkAccountBotUrl = (discordId: number, player: string) => {
	return `${ELITE_API_URL}/bot/account/${discordId}/${player}`;
};

/**
 * @summary Link Account
 */
export const linkAccountBot = async (discordId: number, player: string, options?: RequestInit) => {
	return customFetch<linkAccountBotResponse>(getLinkAccountBotUrl(discordId, player), {
		...options,
		method: 'POST',
	});
};

export type unlinkAccountBotResponse204 = {
	data: void;
	status: 204;
};

export type unlinkAccountBotResponse400 = {
	data: ProblemDetails;
	status: 400;
};

export type unlinkAccountBotResponseSuccess = unlinkAccountBotResponse204 & {
	headers: Headers;
};
export type unlinkAccountBotResponseError = unlinkAccountBotResponse400 & {
	headers: Headers;
};

export type unlinkAccountBotResponse = unlinkAccountBotResponseSuccess | unlinkAccountBotResponseError;

export const getUnlinkAccountBotUrl = (discordId: number, player: string) => {
	return `${ELITE_API_URL}/bot/account/${discordId}/${player}`;
};

/**
 * @summary Unlink Account
 */
export const unlinkAccountBot = async (discordId: number, player: string, options?: RequestInit) => {
	return customFetch<unlinkAccountBotResponse>(getUnlinkAccountBotUrl(discordId, player), {
		...options,
		method: 'DELETE',
	});
};

export type makePrimaryAccountResponse204 = {
	data: void;
	status: 204;
};

export type makePrimaryAccountResponse400 = {
	data: ProblemDetails;
	status: 400;
};

export type makePrimaryAccountResponseSuccess = makePrimaryAccountResponse204 & {
	headers: Headers;
};
export type makePrimaryAccountResponseError = makePrimaryAccountResponse400 & {
	headers: Headers;
};

export type makePrimaryAccountResponse = makePrimaryAccountResponseSuccess | makePrimaryAccountResponseError;

export const getMakePrimaryAccountUrl = (discordId: number, player: string) => {
	return `${ELITE_API_URL}/bot/account/${discordId}/${player}/primary`;
};

/**
 * @summary Make Primary Account
 */
export const makePrimaryAccount = async (discordId: number, player: string, options?: RequestInit) => {
	return customFetch<makePrimaryAccountResponse>(getMakePrimaryAccountUrl(discordId, player), {
		...options,
		method: 'POST',
	});
};

export type grantBadgeResponse204 = {
	data: void;
	status: 204;
};

export type grantBadgeResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type grantBadgeResponseSuccess = grantBadgeResponse204 & {
	headers: Headers;
};
export type grantBadgeResponseError = grantBadgeResponse400 & {
	headers: Headers;
};

export type grantBadgeResponse = grantBadgeResponseSuccess | grantBadgeResponseError;

export const getGrantBadgeUrl = (player: string, badgeId: number) => {
	return `${ELITE_API_URL}/bot/badges/${player}/${badgeId}`;
};

/**
 * @summary Grant Badge
 */
export const grantBadge = async (player: string, badgeId: number, options?: RequestInit) => {
	return customFetch<grantBadgeResponse>(getGrantBadgeUrl(player, badgeId), {
		...options,
		method: 'POST',
	});
};

export type getContestPingsResponse200 = {
	data: ListOfContestPingsFeatureDto;
	status: 200;
};

export type getContestPingsResponseSuccess = getContestPingsResponse200 & {
	headers: Headers;
};

export type getContestPingsResponse = getContestPingsResponseSuccess;

export const getGetContestPingsUrl = () => {
	return `${ELITE_API_URL}/bot/contestpings`;
};

/**
 * @summary Get list of guilds with contest pings enabled
 */
export const getContestPings = async (options?: RequestInit) => {
	return customFetch<getContestPingsResponse>(getGetContestPingsUrl(), {
		...options,
		method: 'GET',
	});
};

export type disableContestPingsPingsResponse204 = {
	data: void;
	status: 204;
};

export type disableContestPingsPingsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type disableContestPingsPingsResponseSuccess = disableContestPingsPingsResponse204 & {
	headers: Headers;
};
export type disableContestPingsPingsResponseError = disableContestPingsPingsResponse400 & {
	headers: Headers;
};

export type disableContestPingsPingsResponse =
	| disableContestPingsPingsResponseSuccess
	| disableContestPingsPingsResponseError;

export const getDisableContestPingsPingsUrl = (discordId: number, params?: DisableContestPingsPingsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/bot/contestpings/${discordId}?${stringifiedParams}`
		: `${ELITE_API_URL}/bot/contestpings/${discordId}`;
};

/**
 * @summary Disable contest pings for a guild
 */
export const disableContestPingsPings = async (
	discordId: number,
	params?: DisableContestPingsPingsParams,
	options?: RequestInit,
) => {
	return customFetch<disableContestPingsPingsResponse>(getDisableContestPingsPingsUrl(discordId, params), {
		...options,
		method: 'DELETE',
	});
};

export type refreshGuildResponse204 = {
	data: void;
	status: 204;
};

export type refreshGuildResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type refreshGuildResponseSuccess = refreshGuildResponse204 & {
	headers: Headers;
};
export type refreshGuildResponseError = refreshGuildResponse400 & {
	headers: Headers;
};

export type refreshGuildResponse = refreshGuildResponseSuccess | refreshGuildResponseError;

export const getRefreshGuildUrl = (discordId: number) => {
	return `${ELITE_API_URL}/bot/guild/${discordId}`;
};

/**
 * @summary Request Guild Update
 */
export const refreshGuild = async (discordId: number, options?: RequestInit) => {
	return customFetch<refreshGuildResponse>(getRefreshGuildUrl(discordId), {
		...options,
		method: 'POST',
	});
};

export type removeGuildResponse204 = {
	data: void;
	status: 204;
};

export type removeGuildResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type removeGuildResponseSuccess = removeGuildResponse204 & {
	headers: Headers;
};
export type removeGuildResponseError = removeGuildResponse400 & {
	headers: Headers;
};

export type removeGuildResponse = removeGuildResponseSuccess | removeGuildResponseError;

export const getRemoveGuildUrl = (discordId: number) => {
	return `${ELITE_API_URL}/bot/guild/${discordId}`;
};

/**
 * @summary Mark a guild as no longer containing the bot
 */
export const removeGuild = async (discordId: number, options?: RequestInit) => {
	return customFetch<removeGuildResponse>(getRemoveGuildUrl(discordId), {
		...options,
		method: 'DELETE',
	});
};

export type updateGuildChannelResponse204 = {
	data: void;
	status: 204;
};

export type updateGuildChannelResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type updateGuildChannelResponseSuccess = updateGuildChannelResponse204 & {
	headers: Headers;
};
export type updateGuildChannelResponseError = updateGuildChannelResponse400 & {
	headers: Headers;
};

export type updateGuildChannelResponse = updateGuildChannelResponseSuccess | updateGuildChannelResponseError;

export const getUpdateGuildChannelUrl = (discordId: number) => {
	return `${ELITE_API_URL}/bot/guild/${discordId}/channels`;
};

/**
 * @summary Update Guild Channel
 */
export const updateGuildChannel = async (
	discordId: number,
	incomingGuildChannelDto: IncomingGuildChannelDto,
	options?: RequestInit,
) => {
	return customFetch<updateGuildChannelResponse>(getUpdateGuildChannelUrl(discordId), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(incomingGuildChannelDto),
	});
};

export type updateGuildMemberRolesResponse204 = {
	data: void;
	status: 204;
};

export type updateGuildMemberRolesResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type updateGuildMemberRolesResponseSuccess = updateGuildMemberRolesResponse204 & {
	headers: Headers;
};
export type updateGuildMemberRolesResponseError = updateGuildMemberRolesResponse400 & {
	headers: Headers;
};

export type updateGuildMemberRolesResponse =
	| updateGuildMemberRolesResponseSuccess
	| updateGuildMemberRolesResponseError;

export const getUpdateGuildMemberRolesUrl = (discordId: number, userId: string) => {
	return `${ELITE_API_URL}/bot/guild/${discordId}/members/${userId}/roles`;
};

/**
 * @summary Update Guild Member Roles
 */
export const updateGuildMemberRoles = async (
	discordId: number,
	userId: string,
	listOfString: ListOfString,
	options?: RequestInit,
) => {
	return customFetch<updateGuildMemberRolesResponse>(getUpdateGuildMemberRolesUrl(discordId, userId), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(listOfString),
	});
};

export type updateGuildRoleResponse204 = {
	data: void;
	status: 204;
};

export type updateGuildRoleResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type updateGuildRoleResponseSuccess = updateGuildRoleResponse204 & {
	headers: Headers;
};
export type updateGuildRoleResponseError = updateGuildRoleResponse400 & {
	headers: Headers;
};

export type updateGuildRoleResponse = updateGuildRoleResponseSuccess | updateGuildRoleResponseError;

export const getUpdateGuildRoleUrl = (discordId: number) => {
	return `${ELITE_API_URL}/bot/guild/${discordId}/roles`;
};

/**
 * @summary Update Guild Role
 */
export const updateGuildRole = async (
	discordId: number,
	incomingGuildRoleDto: IncomingGuildRoleDto,
	options?: RequestInit,
) => {
	return customFetch<updateGuildRoleResponse>(getUpdateGuildRoleUrl(discordId), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(incomingGuildRoleDto),
	});
};

export type updateNotificationDeliveryAttemptResponse204 = {
	data: void;
	status: 204;
};

export type updateNotificationDeliveryAttemptResponse401 = {
	data: void;
	status: 401;
};

export type updateNotificationDeliveryAttemptResponseSuccess = updateNotificationDeliveryAttemptResponse204 & {
	headers: Headers;
};
export type updateNotificationDeliveryAttemptResponseError = updateNotificationDeliveryAttemptResponse401 & {
	headers: Headers;
};

export type updateNotificationDeliveryAttemptResponse =
	| updateNotificationDeliveryAttemptResponseSuccess
	| updateNotificationDeliveryAttemptResponseError;

export const getUpdateNotificationDeliveryAttemptUrl = (attemptId: string) => {
	return `${ELITE_API_URL}/bot/notifications/delivery-attempts/${attemptId}`;
};

/**
 * @summary Update notification delivery attempt status
 */
export const updateNotificationDeliveryAttempt = async (
	attemptId: string,
	updateNotificationDeliveryAttemptRequest: UpdateNotificationDeliveryAttemptRequest,
	options?: RequestInit,
) => {
	return customFetch<updateNotificationDeliveryAttemptResponse>(getUpdateNotificationDeliveryAttemptUrl(attemptId), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(updateNotificationDeliveryAttemptRequest),
	});
};

export type getBotGuildResponse200 = {
	data: PrivateGuildDto;
	status: 200;
};

export type getBotGuildResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getBotGuildResponseSuccess = getBotGuildResponse200 & {
	headers: Headers;
};
export type getBotGuildResponseError = getBotGuildResponse400 & {
	headers: Headers;
};

export type getBotGuildResponse = getBotGuildResponseSuccess | getBotGuildResponseError;

export const getGetBotGuildUrl = (discordId: number) => {
	return `${ELITE_API_URL}/bot/${discordId}`;
};

/**
 * @summary Get guild
 */
export const getBotGuild = async (discordId: number, options?: RequestInit) => {
	return customFetch<getBotGuildResponse>(getGetBotGuildUrl(discordId), {
		...options,
		method: 'GET',
	});
};

export type getJacobFeatureResponse200 = {
	data: GuildJacobLeaderboardFeature;
	status: 200;
};

export type getJacobFeatureResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getJacobFeatureResponseSuccess = getJacobFeatureResponse200 & {
	headers: Headers;
};
export type getJacobFeatureResponseError = getJacobFeatureResponse400 & {
	headers: Headers;
};

export type getJacobFeatureResponse = getJacobFeatureResponseSuccess | getJacobFeatureResponseError;

export const getGetJacobFeatureUrl = (discordId: number) => {
	return `${ELITE_API_URL}/bot/${discordId}/jacob`;
};

/**
 * @summary Get guild jacob
 */
export const getJacobFeature = async (discordId: number, options?: RequestInit) => {
	return customFetch<getJacobFeatureResponse>(getGetJacobFeatureUrl(discordId), {
		...options,
		method: 'GET',
	});
};

export type updateJacobFeatureResponse200 = {
	data: GuildJacobLeaderboardFeature;
	status: 200;
};

export type updateJacobFeatureResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type updateJacobFeatureResponseSuccess = updateJacobFeatureResponse200 & {
	headers: Headers;
};
export type updateJacobFeatureResponseError = updateJacobFeatureResponse400 & {
	headers: Headers;
};

export type updateJacobFeatureResponse = updateJacobFeatureResponseSuccess | updateJacobFeatureResponseError;

export const getUpdateJacobFeatureUrl = (discordId: number, params?: UpdateJacobFeatureParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/bot/${discordId}/jacob?${stringifiedParams}`
		: `${ELITE_API_URL}/bot/${discordId}/jacob`;
};

/**
 * @summary Update guild jacob feature
 */
export const updateJacobFeature = async (
	discordId: number,
	updateJacobFeatureRequestUpdateJacobFeature: UpdateJacobFeatureRequestUpdateJacobFeature,
	params?: UpdateJacobFeatureParams,
	options?: RequestInit,
) => {
	return customFetch<updateJacobFeatureResponse>(getUpdateJacobFeatureUrl(discordId, params), {
		...options,
		method: 'PUT',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(updateJacobFeatureRequestUpdateJacobFeature),
	});
};

export type getCurrentContestsResponse200 = {
	data: YearlyContestsDto;
	status: 200;
};

export type getCurrentContestsResponseSuccess = getCurrentContestsResponse200 & {
	headers: Headers;
};

export type getCurrentContestsResponse = getCurrentContestsResponseSuccess;

export const getGetCurrentContestsUrl = () => {
	return `${ELITE_API_URL}/contests/at/now`;
};

/**
 * Uses crowd-sourced data, which may not be accurate.
 * Data used and provided by <see href="https://github.com/hannibal002/SkyHanni/">SkyHanni</see> to display upcoming contests in-game.
 * @summary Get upcoming contests for the current SkyBlock year
 */
export const getCurrentContests = async (options?: RequestInit) => {
	return customFetch<getCurrentContestsResponse>(getGetCurrentContestsUrl(), {
		...options,
		method: 'GET',
	});
};

export type getPlayerParticipationsResponse200 = {
	data: ListOfContestParticipationDto;
	status: 200;
};

export type getPlayerParticipationsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getPlayerParticipationsResponseSuccess = getPlayerParticipationsResponse200 & {
	headers: Headers;
};
export type getPlayerParticipationsResponseError = getPlayerParticipationsResponse400 & {
	headers: Headers;
};

export type getPlayerParticipationsResponse =
	| getPlayerParticipationsResponseSuccess
	| getPlayerParticipationsResponseError;

export const getGetPlayerParticipationsUrl = (playerUuid: string) => {
	return `${ELITE_API_URL}/contests/${playerUuid}`;
};

/**
 * @summary Get all contests for a player
 */
export const getPlayerParticipations = async (playerUuid: string, options?: RequestInit) => {
	return customFetch<getPlayerParticipationsResponse>(getGetPlayerParticipationsUrl(playerUuid), {
		...options,
		method: 'GET',
	});
};

export type getContestsAtTimestampResponse200 = {
	data: ListOfJacobContestWithParticipationsDto;
	status: 200;
};

export type getContestsAtTimestampResponseSuccess = getContestsAtTimestampResponse200 & {
	headers: Headers;
};

export type getContestsAtTimestampResponse = getContestsAtTimestampResponseSuccess;

export const getGetContestsAtTimestampUrl = (timestamp: number, params: GetContestsAtTimestampParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/contests/${timestamp}?${stringifiedParams}`
		: `${ELITE_API_URL}/contests/${timestamp}`;
};

/**
 * @summary Get the three contests that start at a specific timestamp
 */
export const getContestsAtTimestamp = async (
	timestamp: number,
	params: GetContestsAtTimestampParams,
	options?: RequestInit,
) => {
	return customFetch<getContestsAtTimestampResponse>(getGetContestsAtTimestampUrl(timestamp, params), {
		...options,
		method: 'GET',
	});
};

export type getCurrentMedalBracketsResponse200 = {
	data: ContestBracketsDetailsDto;
	status: 200;
};

export type getCurrentMedalBracketsResponseSuccess = getCurrentMedalBracketsResponse200 & {
	headers: Headers;
};

export type getCurrentMedalBracketsResponse = getCurrentMedalBracketsResponseSuccess;

export const getGetCurrentMedalBracketsUrl = (params?: GetCurrentMedalBracketsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/graph/medals/now?${stringifiedParams}`
		: `${ELITE_API_URL}/graph/medals/now`;
};

/**
 * @summary Get current average medal brackets
 */
export const getCurrentMedalBrackets = async (params?: GetCurrentMedalBracketsParams, options?: RequestInit) => {
	return customFetch<getCurrentMedalBracketsResponse>(getGetCurrentMedalBracketsUrl(params), {
		...options,
		method: 'GET',
	});
};

export type getMedalBracketsGraphResponse200 = {
	data: ListOfContestBracketsDetailsDto;
	status: 200;
};

export type getMedalBracketsGraphResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getMedalBracketsGraphResponseSuccess = getMedalBracketsGraphResponse200 & {
	headers: Headers;
};
export type getMedalBracketsGraphResponseError = getMedalBracketsGraphResponse400 & {
	headers: Headers;
};

export type getMedalBracketsGraphResponse = getMedalBracketsGraphResponseSuccess | getMedalBracketsGraphResponseError;

export const getGetMedalBracketsGraphUrl = (year: number, params?: GetMedalBracketsGraphParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/graph/medals/${year}?${stringifiedParams}`
		: `${ELITE_API_URL}/graph/medals/${year}`;
};

/**
 * @summary Get average medal brackets for multiple SkyBlock years
 */
export const getMedalBracketsGraph = async (
	year: number,
	params?: GetMedalBracketsGraphParams,
	options?: RequestInit,
) => {
	return customFetch<getMedalBracketsGraphResponse>(getGetMedalBracketsGraphUrl(year, params), {
		...options,
		method: 'GET',
	});
};

export type getMedalBracketsResponse200 = {
	data: ContestBracketsDetailsDto;
	status: 200;
};

export type getMedalBracketsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getMedalBracketsResponseSuccess = getMedalBracketsResponse200 & {
	headers: Headers;
};
export type getMedalBracketsResponseError = getMedalBracketsResponse400 & {
	headers: Headers;
};

export type getMedalBracketsResponse = getMedalBracketsResponseSuccess | getMedalBracketsResponseError;

export const getGetMedalBracketsUrl = (year: number, month: number, params?: GetMedalBracketsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/graph/medals/${year}/${month}?${stringifiedParams}`
		: `${ELITE_API_URL}/graph/medals/${year}/${month}`;
};

/**
 * @summary Get average medal brackets for a specific SkyBlock month
 */
export const getMedalBrackets = async (
	year: number,
	month: number,
	params?: GetMedalBracketsParams,
	options?: RequestInit,
) => {
	return customFetch<getMedalBracketsResponse>(getGetMedalBracketsUrl(year, month, params), {
		...options,
		method: 'GET',
	});
};

export type getCropGraphsResponse200 = {
	data: ListOfCropCollectionsDataPointDto;
	status: 200;
};

export type getCropGraphsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getCropGraphsResponseSuccess = getCropGraphsResponse200 & {
	headers: Headers;
};
export type getCropGraphsResponseError = getCropGraphsResponse400 & {
	headers: Headers;
};

export type getCropGraphsResponse = getCropGraphsResponseSuccess | getCropGraphsResponseError;

export const getGetCropGraphsUrl = (playerUuid: string, profileUuid: string, params?: GetCropGraphsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/graph/${playerUuid}/${profileUuid}/crops?${stringifiedParams}`
		: `${ELITE_API_URL}/graph/${playerUuid}/${profileUuid}/crops`;
};

/**
 * @summary Get Crop Collections Over Time
 */
export const getCropGraphs = async (
	playerUuid: string,
	profileUuid: string,
	params?: GetCropGraphsParams,
	options?: RequestInit,
) => {
	return customFetch<getCropGraphsResponse>(getGetCropGraphsUrl(playerUuid, profileUuid, params), {
		...options,
		method: 'GET',
	});
};

export type getSkillGraphsResponse200 = {
	data: ListOfSkillsDataPointDto;
	status: 200;
};

export type getSkillGraphsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getSkillGraphsResponseSuccess = getSkillGraphsResponse200 & {
	headers: Headers;
};
export type getSkillGraphsResponseError = getSkillGraphsResponse400 & {
	headers: Headers;
};

export type getSkillGraphsResponse = getSkillGraphsResponseSuccess | getSkillGraphsResponseError;

export const getGetSkillGraphsUrl = (playerUuid: string, profileUuid: string, params?: GetSkillGraphsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/graph/${playerUuid}/${profileUuid}/skills?${stringifiedParams}`
		: `${ELITE_API_URL}/graph/${playerUuid}/${profileUuid}/skills`;
};

/**
 * @summary Get Skill XP Over Time
 */
export const getSkillGraphs = async (
	playerUuid: string,
	profileUuid: string,
	params?: GetSkillGraphsParams,
	options?: RequestInit,
) => {
	return customFetch<getSkillGraphsResponse>(getGetSkillGraphsUrl(playerUuid, profileUuid, params), {
		...options,
		method: 'GET',
	});
};

export type getGuideResponse200 = {
	data: FullGuideDto;
	status: 200;
};

export type getGuideResponseSuccess = getGuideResponse200 & {
	headers: Headers;
};

export type getGuideResponse = getGuideResponseSuccess;

export const getGetGuideUrl = (slug: string, params: GetGuideParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/guides/${slug}?${stringifiedParams}`
		: `${ELITE_API_URL}/guides/${slug}`;
};

/**
 * Retrieve a guide by its slug. Use ?draft=true to view draft version (requires author/mod permission).
 * @summary Get a guide
 */
export const getGuide = async (slug: string, params: GetGuideParams, options?: RequestInit) => {
	return customFetch<getGuideResponse>(getGetGuideUrl(slug, params), {
		...options,
		method: 'GET',
	});
};

export type getPlayerRank1Response200 = {
	data: LeaderboardPositionDto;
	status: 200;
};

export type getPlayerRank1Response400 = {
	data: ErrorResponse;
	status: 400;
};

export type getPlayerRank1ResponseSuccess = getPlayerRank1Response200 & {
	headers: Headers;
};
export type getPlayerRank1ResponseError = getPlayerRank1Response400 & {
	headers: Headers;
};

export type getPlayerRank1Response = getPlayerRank1ResponseSuccess | getPlayerRank1ResponseError;

export const getGetPlayerRank1Url = (
	leaderboard: string,
	playerUuid: string,
	profileUuid: string,
	params?: GetPlayerRank1Params,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/leaderboard/rank/${leaderboard}/${playerUuid}/${profileUuid}?${stringifiedParams}`
		: `${ELITE_API_URL}/leaderboard/rank/${leaderboard}/${playerUuid}/${profileUuid}`;
};

/**
 * @summary Get a Player's Leaderboard Rank
 */
export const getPlayerRank1 = async (
	leaderboard: string,
	playerUuid: string,
	profileUuid: string,
	params?: GetPlayerRank1Params,
	options?: RequestInit,
) => {
	return customFetch<getPlayerRank1Response>(getGetPlayerRank1Url(leaderboard, playerUuid, profileUuid, params), {
		...options,
		method: 'GET',
	});
};

export type getLeaderboardResponse200 = {
	data: LeaderboardDto;
	status: 200;
};

export type getLeaderboardResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getLeaderboardResponseSuccess = getLeaderboardResponse200 & {
	headers: Headers;
};
export type getLeaderboardResponseError = getLeaderboardResponse400 & {
	headers: Headers;
};

export type getLeaderboardResponse = getLeaderboardResponseSuccess | getLeaderboardResponseError;

export const getGetLeaderboardUrl = (leaderboard: string, params?: GetLeaderboardParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/leaderboard/${leaderboard}?${stringifiedParams}`
		: `${ELITE_API_URL}/leaderboard/${leaderboard}`;
};

/**
 * @summary Get Leaderboard
 */
export const getLeaderboard = async (leaderboard: string, params?: GetLeaderboardParams, options?: RequestInit) => {
	return customFetch<getLeaderboardResponse>(getGetLeaderboardUrl(leaderboard, params), {
		...options,
		method: 'GET',
	});
};

export type getPlayerRank2Response200 = {
	data: LeaderboardPositionDto;
	status: 200;
};

export type getPlayerRank2Response400 = {
	data: ErrorResponse;
	status: 400;
};

export type getPlayerRank2ResponseSuccess = getPlayerRank2Response200 & {
	headers: Headers;
};
export type getPlayerRank2ResponseError = getPlayerRank2Response400 & {
	headers: Headers;
};

export type getPlayerRank2Response = getPlayerRank2ResponseSuccess | getPlayerRank2ResponseError;

export const getGetPlayerRank2Url = (
	leaderboard: string,
	playerUuid: string,
	profileUuid: string,
	params?: GetPlayerRank2Params,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/leaderboard/${leaderboard}/${playerUuid}/${profileUuid}?${stringifiedParams}`
		: `${ELITE_API_URL}/leaderboard/${leaderboard}/${playerUuid}/${profileUuid}`;
};

/**
 * @summary Get a Player's Leaderboard Rank
 */
export const getPlayerRank2 = async (
	leaderboard: string,
	playerUuid: string,
	profileUuid: string,
	params?: GetPlayerRank2Params,
	options?: RequestInit,
) => {
	return customFetch<getPlayerRank2Response>(getGetPlayerRank2Url(leaderboard, playerUuid, profileUuid, params), {
		...options,
		method: 'GET',
	});
};

export type getLeaderboardsResponse200 = {
	data: LeaderboardsResponse;
	status: 200;
};

export type getLeaderboardsResponseSuccess = getLeaderboardsResponse200 & {
	headers: Headers;
};

export type getLeaderboardsResponse = getLeaderboardsResponseSuccess;

export const getGetLeaderboardsUrl = () => {
	return `${ELITE_API_URL}/leaderboards`;
};

/**
 * @summary Get Leaderboards
 */
export const getLeaderboards = async (options?: RequestInit) => {
	return customFetch<getLeaderboardsResponse>(getGetLeaderboardsUrl(), {
		...options,
		method: 'GET',
	});
};

export type getPlayerLeaderboardRanksResponse200 = {
	data: LeaderboardRanksResponse;
	status: 200;
};

export type getPlayerLeaderboardRanksResponseSuccess = getPlayerLeaderboardRanksResponse200 & {
	headers: Headers;
};

export type getPlayerLeaderboardRanksResponse = getPlayerLeaderboardRanksResponseSuccess;

export const getGetPlayerLeaderboardRanksUrl = (
	playerUuid: string,
	profileUuid: string,
	params?: GetPlayerLeaderboardRanksParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/leaderboards/${playerUuid}/${profileUuid}?${stringifiedParams}`
		: `${ELITE_API_URL}/leaderboards/${playerUuid}/${profileUuid}`;
};

/**
 * @summary Get a Player's Leaderboard Ranks
 */
export const getPlayerLeaderboardRanks = async (
	playerUuid: string,
	profileUuid: string,
	params?: GetPlayerLeaderboardRanksParams,
	options?: RequestInit,
) => {
	return customFetch<getPlayerLeaderboardRanksResponse>(
		getGetPlayerLeaderboardRanksUrl(playerUuid, profileUuid, params),
		{
			...options,
			method: 'GET',
		},
	);
};

export type getPlayerDataResponse200 = {
	data: PlayerDataDto;
	status: 200;
};

export type getPlayerDataResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getPlayerDataResponse404 = {
	data: void;
	status: 404;
};

export type getPlayerDataResponseSuccess = getPlayerDataResponse200 & {
	headers: Headers;
};
export type getPlayerDataResponseError = (getPlayerDataResponse400 | getPlayerDataResponse404) & {
	headers: Headers;
};

export type getPlayerDataResponse = getPlayerDataResponseSuccess | getPlayerDataResponseError;

export const getGetPlayerDataUrl = (player: string) => {
	return `${ELITE_API_URL}/player/${player}`;
};

/**
 * @summary Get Player Data
 */
export const getPlayerData = async (player: string, options?: RequestInit) => {
	return customFetch<getPlayerDataResponse>(getGetPlayerDataUrl(player), {
		...options,
		method: 'GET',
	});
};

export type getStylesResponse200 = {
	data: ListOfWeightStyleListDto;
	status: 200;
};

export type getStylesResponseSuccess = getStylesResponse200 & {
	headers: Headers;
};

export type getStylesResponse = getStylesResponseSuccess;

export const getGetStylesUrl = () => {
	return `${ELITE_API_URL}/product/styles`;
};

/**
 * @summary Get Shop Styles
 */
export const getStyles = async (options?: RequestInit) => {
	return customFetch<getStylesResponse>(getGetStylesUrl(), {
		...options,
		method: 'GET',
	});
};

export type getProductResponse200 = {
	data: ProductDto;
	status: 200;
};

export type getProductResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getProductResponseSuccess = getProductResponse200 & {
	headers: Headers;
};
export type getProductResponseError = getProductResponse400 & {
	headers: Headers;
};

export type getProductResponse = getProductResponseSuccess | getProductResponseError;

export const getGetProductUrl = (discordId: number) => {
	return `${ELITE_API_URL}/product/${discordId}`;
};

/**
 * @summary Get Shop Product
 */
export const getProduct = async (discordId: number, options?: RequestInit) => {
	return customFetch<getProductResponse>(getGetProductUrl(discordId), {
		...options,
		method: 'GET',
	});
};

export type getSelectedProfileResponse200 = {
	data: ProfileMemberDto;
	status: 200;
};

export type getSelectedProfileResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getSelectedProfileResponse404 = {
	data: void;
	status: 404;
};

export type getSelectedProfileResponseSuccess = getSelectedProfileResponse200 & {
	headers: Headers;
};
export type getSelectedProfileResponseError = (getSelectedProfileResponse400 | getSelectedProfileResponse404) & {
	headers: Headers;
};

export type getSelectedProfileResponse = getSelectedProfileResponseSuccess | getSelectedProfileResponseError;

export const getGetSelectedProfileUrl = (playerUuid: string) => {
	return `${ELITE_API_URL}/profile/${playerUuid}/selected`;
};

/**
 * @summary Get Profile Member
 */
export const getSelectedProfile = async (playerUuid: string, options?: RequestInit) => {
	return customFetch<getSelectedProfileResponse>(getGetSelectedProfileUrl(playerUuid), {
		...options,
		method: 'GET',
	});
};

export type getProfileResponse200 = {
	data: ProfileMemberDto;
	status: 200;
};

export type getProfileResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getProfileResponse404 = {
	data: void;
	status: 404;
};

export type getProfileResponseSuccess = getProfileResponse200 & {
	headers: Headers;
};
export type getProfileResponseError = (getProfileResponse400 | getProfileResponse404) & {
	headers: Headers;
};

export type getProfileResponse = getProfileResponseSuccess | getProfileResponseError;

export const getGetProfileUrl = (playerUuid: string, profileUuid: string) => {
	return `${ELITE_API_URL}/profile/${playerUuid}/${profileUuid}`;
};

/**
 * @summary Get Profile Member
 */
export const getProfile = async (playerUuid: string, profileUuid: string, options?: RequestInit) => {
	return customFetch<getProfileResponse>(getGetProfileUrl(playerUuid, profileUuid), {
		...options,
		method: 'GET',
	});
};

export type getVirtualFarmingInventoryResponse200 = {
	data: FarmingInventoryDto;
	status: 200;
};

export type getVirtualFarmingInventoryResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getVirtualFarmingInventoryResponse404 = {
	data: void;
	status: 404;
};

export type getVirtualFarmingInventoryResponseSuccess = getVirtualFarmingInventoryResponse200 & {
	headers: Headers;
};
export type getVirtualFarmingInventoryResponseError = (
	| getVirtualFarmingInventoryResponse400
	| getVirtualFarmingInventoryResponse404
) & {
	headers: Headers;
};

export type getVirtualFarmingInventoryResponse =
	| getVirtualFarmingInventoryResponseSuccess
	| getVirtualFarmingInventoryResponseError;

export const getGetVirtualFarmingInventoryUrl = (playerUuid: string, profileUuid: string) => {
	return `${ELITE_API_URL}/profile/${playerUuid}/${profileUuid}/inventories/virtual/farming`;
};

/**
 * @summary Get virtual farming inventory
 */
export const getVirtualFarmingInventory = async (playerUuid: string, profileUuid: string, options?: RequestInit) => {
	return customFetch<getVirtualFarmingInventoryResponse>(getGetVirtualFarmingInventoryUrl(playerUuid, profileUuid), {
		...options,
		method: 'GET',
	});
};

export type getSpecifiedSkyblockItemsResponse200 = {
	data: GetSpecifiedSkyblockItemsResponse;
	status: 200;
};

export type getSpecifiedSkyblockItemsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type getSpecifiedSkyblockItemsResponseSuccess = getSpecifiedSkyblockItemsResponse200 & {
	headers: Headers;
};
export type getSpecifiedSkyblockItemsResponseError = getSpecifiedSkyblockItemsResponse400 & {
	headers: Headers;
};

export type getSpecifiedSkyblockItemsResponse =
	| getSpecifiedSkyblockItemsResponseSuccess
	| getSpecifiedSkyblockItemsResponseError;

export const getGetSpecifiedSkyblockItemsUrl = () => {
	return `${ELITE_API_URL}/resources/items`;
};

/**
 * Get specific skyblock items from the Hypixel resources endpoint, along with bazaar data for each.
 * @summary Get Specific Skyblock Items
 */
export const getSpecifiedSkyblockItems = async (
	getSpecifiedSkyblockItemsRequest: GetSpecifiedSkyblockItemsRequest,
	options?: RequestInit,
) => {
	return customFetch<getSpecifiedSkyblockItemsResponse>(getGetSpecifiedSkyblockItemsUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(getSpecifiedSkyblockItemsRequest),
	});
};

export type submitScoreResponse200 = {
	data: SubmitScoreResponse;
	status: 200;
};

export type submitScoreResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type submitScoreResponseSuccess = submitScoreResponse200 & {
	headers: Headers;
};
export type submitScoreResponseError = submitScoreResponse400 & {
	headers: Headers;
};

export type submitScoreResponse = submitScoreResponseSuccess | submitScoreResponseError;

export const getSubmitScoreUrl = (discordId: number, leaderboardId: string, params?: SubmitScoreParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/user/guild/${discordId}/jacob/${leaderboardId}/submit?${stringifiedParams}`
		: `${ELITE_API_URL}/user/guild/${discordId}/jacob/${leaderboardId}/submit`;
};

/**
 * @summary Submit scores to a Jacob leaderboard
 */
export const submitScore = async (
	discordId: number,
	leaderboardId: string,
	listOfString: ListOfString,
	params?: SubmitScoreParams,
	options?: RequestInit,
) => {
	return customFetch<submitScoreResponse>(getSubmitScoreUrl(discordId, leaderboardId, params), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(listOfString),
	});
};

export type getWeightForProfilesResponse200 = {
	data: FarmingWeightAllProfilesDto;
	status: 200;
};

export type getWeightForProfilesResponse404 = {
	data: void;
	status: 404;
};

export type getWeightForProfilesResponseSuccess = getWeightForProfilesResponse200 & {
	headers: Headers;
};
export type getWeightForProfilesResponseError = getWeightForProfilesResponse404 & {
	headers: Headers;
};

export type getWeightForProfilesResponse = getWeightForProfilesResponseSuccess | getWeightForProfilesResponseError;

export const getGetWeightForProfilesUrl = (playerUuid: string, params?: GetWeightForProfilesParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${ELITE_API_URL}/weight/${playerUuid}?${stringifiedParams}`
		: `${ELITE_API_URL}/weight/${playerUuid}`;
};

/**
 * Get farming weight for all profiles of a player
 * @summary Get farming weight for all profiles of a player
 */
export const getWeightForProfiles = async (
	playerUuid: string,
	params?: GetWeightForProfilesParams,
	options?: RequestInit,
) => {
	return customFetch<getWeightForProfilesResponse>(getGetWeightForProfilesUrl(playerUuid, params), {
		...options,
		method: 'GET',
	});
};
